// 14 factions with colors, descriptions, roles, and spawn zones

export const FACTIONS = [
  {
    id: 'class-d',
    name: 'Class-D',
    shortName: 'D-Class',
    color: '#d4a017',
    description: 'Disposable test subjects drawn from death row. They survive day to day by following orders — or by escaping.',
    role: 'Test subjects / escapees',
    spawnZone: 'class-d',
    category: 'contained',
    hostile: ['security', 'mtf-nu7', 'mtf-epsilon11', 'mtf-alpha1', 'intel', 'internal-security'],
  },
  {
    id: 'scientific',
    name: 'Scientific Department',
    shortName: 'Sci Dept',
    color: '#f0e68c',
    description: 'Researchers who study anomalous objects. They run tests on SCPs and Class-D personnel, balancing discovery with containment.',
    role: 'Research & testing',
    spawnZone: 'scientific',
    category: 'foundation',
    hostile: ['chaos'],
  },
  {
    id: 'security',
    name: 'Security Department',
    shortName: 'Security',
    color: '#4a90d9',
    description: 'Facility guards responsible for maintaining order, escorting Class-D, and responding to containment breaches.',
    role: 'Facility security',
    spawnZone: 'security',
    category: 'foundation',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'mtf-nu7',
    name: 'MTF Nu-7 "Hammer Down"',
    shortName: 'Nu-7',
    color: '#2d6a4f',
    description: 'A heavy military battalion specializing in large-scale containment breaches and combat operations against hostile anomalies.',
    role: 'Heavy combat response',
    spawnZone: 'mtf',
    category: 'mtf',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'mtf-beta7',
    name: 'MTF Beta-7 "Maz Hatters"',
    shortName: 'Beta-7',
    color: '#8b5cf6',
    description: 'Specialists in biochemical and anomalous disease containment. They handle outbreaks and hazardous material incidents.',
    role: 'Biohazard response',
    spawnZone: 'mtf',
    category: 'mtf',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'mtf-epsilon11',
    name: 'MTF Epsilon-11 "Nine-Tailed Fox"',
    shortName: 'E-11',
    color: '#e63946',
    description: 'The iconic containment task force. They re-contain breached SCPs and eliminate threats within the facility.',
    role: 'Re-containment',
    spawnZone: 'mtf',
    category: 'mtf',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'mtf-alpha1',
    name: 'MTF Alpha-1 "Red Right Hand"',
    shortName: 'Alpha-1',
    color: '#9b1c1c',
    description: 'The O5 Council\'s personal task force. They handle the most sensitive operations and answer directly to the highest authority.',
    role: 'O5 direct action',
    spawnZone: 'mtf',
    category: 'mtf',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'intel',
    name: 'Intelligence Department',
    shortName: 'Intel',
    color: '#6c5ce7',
    description: 'Gathers and analyzes information on anomalous threats and enemy organizations. They operate in the shadows.',
    role: 'Information & surveillance',
    spawnZone: 'intel',
    category: 'foundation',
    hostile: ['chaos'],
  },
  {
    id: 'internal-security',
    name: 'Internal Security Department',
    shortName: 'ISD',
    color: '#2d3436',
    description: 'Investigates threats from within the Foundation itself. They hunt moles, traitors, and unauthorized activities.',
    role: 'Counter-intelligence',
    spawnZone: 'intel',
    category: 'foundation',
    hostile: ['chaos', 'class-d'],
  },
  {
    id: 'rapid-response',
    name: 'Rapid Response Team',
    shortName: 'RRT',
    color: '#00b894',
    description: 'A quick-deployment force that fills gaps during emergencies. They assist wherever the situation demands it.',
    role: 'Emergency support',
    spawnZone: 'security',
    category: 'foundation',
    hostile: ['class-d', 'chaos'],
  },
  {
    id: 'chaos',
    name: 'Chaos Insurgency',
    shortName: 'CI',
    color: '#2ecc71',
    description: 'A rogue organization that steals anomalous objects for their own purposes. They raid facilities and exploit chaos.',
    role: 'Raiders / hostile',
    spawnZone: 'class-d',
    category: 'hostile',
    hostile: ['security', 'mtf-nu7', 'mtf-epsilon11', 'mtf-alpha1', 'mtf-beta7', 'scientific', 'intel', 'internal-security', 'rapid-response', 'medical', 'admin'],
  },
  {
    id: 'admin',
    name: 'Administration Department',
    shortName: 'Admin',
    color: '#fdcb6e',
    description: 'The bureaucratic backbone of the facility. They manage personnel, resources, and make the decisions that shape operations.',
    role: 'Command & oversight',
    spawnZone: 'admin',
    category: 'foundation',
    hostile: ['chaos'],
  },
  {
    id: 'medical',
    name: 'Medical Department',
    shortName: 'Medical',
    color: '#e84393',
    description: 'Doctors and medics who treat the injured, study anomalous medical conditions, and respond to casualty events.',
    role: 'Healthcare & quarantine',
    spawnZone: 'medical',
    category: 'foundation',
    hostile: ['chaos'],
  },
  {
    id: 'foundation-staff',
    name: 'Foundation Staff',
    shortName: 'Staff',
    color: '#a0a0a0',
    description: 'General facility personnel — janitors, technicians, cooks, and logistics workers who keep the facility running.',
    role: 'Facility operations',
    spawnZone: 'common',
    category: 'civilian',
    hostile: ['chaos'],
  },
];

export const FACTION_MAP = Object.fromEntries(FACTIONS.map(f => [f.id, f]));

export function getFaction(id) {
  return FACTION_MAP[id];
}

export function areHostile(factionA, factionB) {
  const fa = FACTION_MAP[factionA];
  if (!fa) return false;
  return fa.hostile.includes(factionB);
}
